name = "SearchLightSerializerJSON"
uuid = "25576f90-54ed-11ea-1c49-09479fd5c390"
authors = ["Adrian Salceanu <e@essenciary.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"

[compat]
julia = "1"